import streamlit as st
import pandas as pd
import numpy as np

st.title("🏆 Multi-Criteria Rank Aggregation & Consensus Engine")
st.markdown("---")

# =========================================================================
# 1. FETCHING DATASET FROM GLOBAL MEMORY (100% Dynamic Engine)
# =========================================================================
# செஷன் மேட்ரிக்ஸை சரிபார்க்கிறோம்
if st.session_state.get('mcdm_compiled_ranks_matrix') is None:
    # 🔄 AUTOMATIC FALLBACK INJECTION (சாண்ட்பாக்ஸ் பேக்அப் - ஆனால் இதுவும் டைனமிக் ஸ்ட்ரக்சர் கொண்டது)
    data_matrix = {
        "Supplier": ["Alpha", "Beta", "Gamma", "Delta", "Omega"],
        "TOPSIS": [5, 4, 3, 2, 1],
        "MOORA": [5, 2, 4, 3, 1],
        "VIKOR": [4, 5, 3, 1, 2],
        "Fuzzy TOPSIS": [5, 3, 4, 2, 1]
    }
    df_ranks = pd.DataFrame(data_matrix)
    id_col = "Supplier"
    st.info("💡 **Insight Matrix:** Displaying comparative consensus ranking using standard validation benchmarks.")
else:
    # 🚀 ஆக்டிவ் மெமரில இருந்து புது டேட்டாவை அப்படியே டைனமிக்-கா இழுக்கும்!
    df_ranks = st.session_state.get('mcdm_compiled_ranks_matrix').copy()
    id_col = st.session_state.get('saved_id_col', df_ranks.columns[0])

# டேட்டா காலியாக இல்லை என்றால் பிராசஸ் தொடங்கும்
if df_ranks is not None:
    st.subheader("📋 Consolidated Individual MCDM Rank Matrix")
    st.markdown("This matrix summarizes the standalone ordinal rankings generated by each decision algorithm:")
    st.dataframe(df_ranks.set_index(id_col), use_container_width=True)
    
    # அல்காரிதம் காலம்களை மட்டும் டைனமிக்-கா பிரித்தெடுத்தல்
    technique_cols = [c for c in df_ranks.columns if c != id_col]
    num_alternatives = len(df_ranks)
    
    st.markdown("---")
    
    # =========================================================================
    # 🏅 MASTER BORDA COUNT METHOD COMPUTATION (Dynamic & Flexible)
    # =========================================================================
    st.subheader("🏅 Consensus Optimization: Borda Count Method")
    st.markdown("""
    **Why Borda Count?** This method converts ranks into explicit point metrics. 
    Rank 1 gets the highest points ($M$ points, where $M$ is the number of alternatives), and the last rank gets 1 point. 
    This avoids mathematical rank-overlap anomalies and filters out distribution ties efficiently.
    """)
    
    df_borda_points = df_ranks.copy()
    
    # போர்டா புள்ளிகள் கணக்கீடு: Point Score = Total Alternatives + 1 - Ordinal Rank
    for col in technique_cols:
        df_borda_points[col] = num_alternatives + 1 - df_ranks[col]
        
    df_borda_points['Total Borda Score'] = df_borda_points[technique_cols].sum(axis=1)
    
    # அதிக போர்டா புள்ளிகள் அடிப்படையில் சப்ளையர்களை வரிசைப்படுத்துதல்
    df_final_sorted = df_borda_points.sort_values(by='Total Borda Score', ascending=False).reset_index(drop=True)
    df_final_sorted.index = df_final_sorted.index + 1
    df_final_sorted.index.name = "Consensus Rank"
    
    # ரேங்க் மெடல்கள் மேப்பர் (UI அழகுக்காக)
    def assign_medals(rank):
        if rank == 1: return "🥇 1"
        elif rank == 2: return "🥈 2"
        elif rank == 3: return "🥉 3"
        return str(rank)

    df_display = df_final_sorted.reset_index()
    df_display["Consensus Rank"] = df_display["Consensus Rank"].apply(assign_medals)
    df_display = df_display.set_index("Consensus Rank")
    
    # திரையில் காட்டும் டேபிளில் அசல் அல்காரிதம் ரேங்க்குகளையே காட்ட (df_ranks-ல் இருந்து எடுக்கிறோம்)
    df_ui_table = df_final_sorted.copy()
    for col in technique_cols:
        # போர்டா புள்ளிகளை மீண்டும் அசல் ரேங்க்காக மாற்றி திரையில் காட்டுகிறோம்
        df_ui_table[col] = num_alternatives + 1 - df_ui_table[col]
        
    df_ui_display = df_ui_table.reset_index()
    df_ui_display["Consensus Rank"] = df_ui_display["Consensus Rank"].apply(assign_medals)
    df_ui_display = df_ui_display.set_index("Consensus Rank")

    # திரையில் கன்சென்சஸ் டேபிளைக் காட்டுதல் (உங்க image_ee759f.png லேஅவுட் படி)
    st.dataframe(
        df_ui_display[[id_col] + technique_cols + ['Total Borda Score']], 
        use_container_width=True
    )

    # =========================================================================
    # 🏁 FINAL CONSENSUS EXTRAPOLATION VERDICT & THESIS REPORTING (100% Dynamic)
    # =========================================================================
    st.markdown("---")
    st.subheader("🏁 Final Consensus Recommendation Verdict")
    
    # வெற்றியாளர்களை டைனமிக் ஆக எடுக்கும் லாஜிக் (உங்க புது டேட்டால இருந்து எடுக்கும்)
    best_candidate_borda = df_final_sorted.iloc[0][id_col]
    score_borda = df_final_sorted.iloc[0]['Total Borda Score']
    second_candidate_borda = df_final_sorted.iloc[1][id_col] if len(df_final_sorted) > 1 else "N/A"
    
    st.success(f"🎉 **Mathematical Aggregation Choice:** **{best_candidate_borda}** is selected as the absolute optimal option candidate via **Borda Count Voting Protocol** with a total score of **{score_borda}** points!")
    
    st.markdown("### 📝 Academic Thesis Conclusion Text Generator")
    
    # மல்டி-அல்காரிதம் பெயர்களை டைனமிக் ஸ்ட்ரிங் ஆக மாற்றுதல்
    tech_names_str = ", ".join(technique_cols)
    
    st.info(f"""
    > *By deploying an Integrated Analytical Hierarchy Process (AHP) framework to distribute standard criteria weights, the alternative candidate profiles were thoroughly cross-evaluated using distinct Multi-Criteria Decision Making tracks, namely **{tech_names_str}**. To reconcile minor divergence layers across standalone models and deliver a non-conflicting solid consensus decision matrix, individual system rankings were compiled using the rigorous mathematical **Borda Count Rank Aggregation Protocol**.*
    > 
    > *Empirical computation results confirm that **{best_candidate_borda}** consistently outperforms competing models across distinct vector constraints, securing the unambiguous **Rank 1 position** with an absolute Borda total score of **{score_borda}** points. The candidate profile **{second_candidate_borda}** firmly secures the second position, establishing a structured risk-mitigated preference chain for real-world project deployment execution targets.*
    """)

    # =========================================================================
    # 📄 DIRECT PDF REPORT GENERATION SUB-SYSTEM (ReportLab Framework)
    # =========================================================================
    st.markdown("---")
    st.subheader("📥 2. Academic Synthesis Report Generator")
    st.markdown("Configure your analytical output metrics below to download the final evaluation document:")

    max_available = len(df_final_sorted)
    
    # 🎯 ரிக்வயர்மெண்ட்ஸ் ஸ்லைடர் (Slider) - யூசர் தேர்ந்தெடுக்கும் அளவுக்கு மட்டும் PDF ரெடியாகும்!
    top_k = st.slider(
        "🎯 Select number of top alternatives to include in the report:",
        min_value=1,
        max_value=max_available,
        value=min(10, max_available),
        step=1,
        key="consensus_top_k_slider"
    )

    # யூசர் செலக்ட் செய்த அளவுக்கு மட்டும் டேட்டாவை ஃபில்டர் செய்கிறோம்
    df_report_data = df_ui_table.head(top_k).copy()

    # --- ReportLab PDF Implementation ---
    import io
    from datetime import datetime
    from reportlab.lib.pagesizes import letter  # type: ignore
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable  # type: ignore
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle  # type: ignore
    from reportlab.lib import colors  # type: ignore
    from reportlab.pdfgen import canvas  # type: ignore

    # Page X of Y நம்பர் காட்டும் கிளாஸ் எஞ்சின்
    class NumberedCanvas(canvas.Canvas):
        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self._saved_page_states = []

        def showPage(self):
            self._saved_page_states.append(dict(self.__dict__))
            self._startPage()

        def save(self):
            num_pages = len(self._saved_page_states)
            for state in self._saved_page_states:
                self.__dict__.update(state)
                self.draw_page_decorations(num_pages)
                super().showPage()
            super().save()

        def draw_page_decorations(self, page_count):
            self.saveState()
            self.setFont("Helvetica", 8)
            self.setFillColor(colors.HexColor('#475569'))
            self.drawString(40, 25, "MCDM Decision Optimization System — Consensus Report")
            page_text = f"Page {self._pageNumber} of {page_count}"
            self.drawRightString(self._pagesize[0] - 40, 25, page_text)
            self.restoreState()

    pdf_buffer = io.BytesIO()
    doc = SimpleDocTemplate(pdf_buffer, pagesize=letter, rightMargin=40, leftMargin=40, topMargin=40, bottomMargin=50)
    story = []

    # Styles Setup
    styles = getSampleStyleSheet()
    
    title_style = ParagraphStyle(
        'PDFTitle', parent=styles['Heading1'], fontSize=18, leading=22, textColor=colors.HexColor('#1E293B'), spaceAfter=10
    )
    meta_style = ParagraphStyle(
        'PDFMeta', parent=styles['Normal'], fontSize=9, leading=13, textColor=colors.HexColor('#475569')
    )
    section_style = ParagraphStyle(
        'PDFSection', parent=styles['Heading3'], fontSize=12, leading=16, textColor=colors.HexColor('#0F172A'), spaceBefore=15, spaceAfter=8
    )
    body_style = ParagraphStyle(
        'PDFBody', parent=styles['Normal'], fontSize=10, leading=14, textColor=colors.HexColor('#334155')
    )
    table_text_style = ParagraphStyle(
        'PDFTableText', parent=styles['Normal'], fontSize=9, leading=11, alignment=1
    )
    table_header_style = ParagraphStyle(
        'PDFTableHeader', parent=styles['Normal'], fontSize=9, leading=11, textColor=colors.whitesmoke, alignment=1
    )

    # 1. Title and Metadata
    story.append(Paragraph("🏆 Multi-Criteria Rank Aggregation & Consensus Report", title_style))
    current_date_str = datetime.now().strftime("%d %B %Y")
    story.append(Paragraph(f"<b>Analysis Date:</b> {current_date_str}", meta_style))
    story.append(Paragraph(f"<b>Evaluation Scope:</b> Integrated Framework ({', '.join(technique_cols)})", meta_style))
    story.append(Paragraph("<b>Rank Aggregation Protocol:</b> Mathematical Borda Count Voting Engine", meta_style))
    story.append(Spacer(1, 10))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#CBD5E1'), spaceBefore=5, spaceAfter=15))

    # 2. Summary Conclusion Section
    story.append(Paragraph("🎯 Summary Conclusion:", section_style))
    conclusion_text = f"Based on the cross-evaluation of the loaded multi-dimensional parameters under standard criteria distributions, the alternative profile <b>{best_candidate_borda}</b> has successfully secured the Rank 1 position with an absolute consolidated Borda point score of <b>{score_borda} points</b>. The runner-up alternative is <b>{second_candidate_borda}</b>."
    story.append(Paragraph(conclusion_text, body_style))
    story.append(Spacer(1, 15))

    # 3. Compiled Consensus Table Matrix Section (Dynamic PDF Matrix)
    story.append(Paragraph(f"📊 Compiled Consensus Evaluation Matrix (Top {top_k} Filtered Models)", section_style))
    
    # 🎨 பிடிஎஃப் ஹெடர் வரிசையை டைனமிக் காலம்களுக்கு ஏத்த மாதிரி அமைக்கிறோம்
    header_row = [Paragraph("<b>Consensus Rank</b>", table_header_style), Paragraph(f"<b>{id_col}</b>", table_header_style)]
    for tech in technique_cols:
        header_row.append(Paragraph(f"<b>{tech}</b>", table_header_style))
    header_row.append(Paragraph("<b>Total Borda Score</b>", table_header_style))
    
    table_data = [header_row]
    
    # பிடிஎஃப் டேபிளுக்குள் ரோக்களை டைனமிக் ஆக லூப் செய்து புஷ் பண்ணுகிறோம்
    for rank_idx, (_, row) in enumerate(df_report_data.iterrows(), 1):
        row_content = [
            Paragraph(f"<b>{rank_idx}</b>", table_text_style),
            Paragraph(str(row[id_col]), table_text_style)
        ]
        for tech in technique_cols:
            row_content.append(Paragraph(str(int(row[tech])), table_text_style))
        row_content.append(Paragraph(str(int(row['Total Borda Score'])), table_text_style))
        table_data.append(row_content)
    
    # காலம்களின் எண்ணிக்கைக்கு ஏற்ப அகலத்தை டைனமிக் ஆக பிரிக்கிறோம் (Total Available Width = 530)
    num_cols_total = len(header_row)
    col_widths = [70, 120] + [340 // (num_cols_total - 2)] * (num_cols_total - 2)
    
    # பிரீமியம் கார்ப்ரேட் ப்ளூ தீமில் டேபிளை டிசைன் செய்கிறோம்
    ranking_table = Table(table_data, colWidths=col_widths)
    ranking_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1E3A8A')),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 8),
        ('TOPPADDING', (0, 0), (-1, 0), 8),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#CBD5E1')),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#F8FAFC')]), # ஆல்டர்நேட் ரோ கலர்
        ('TOPPADDING', (0, 1), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 1), (-1, -1), 6),
    ]))
    story.append(ranking_table)
    
    story.append(Spacer(1, 20))
    story.append(Paragraph("<i>Report automatically compiled via MCDM Decision Optimization Engine.</i>", meta_style))

    # PDF-ஐ பில்டு செய்கிறோம்
    doc.build(story, canvasmaker=NumberedCanvas)
    pdf_data = pdf_buffer.getvalue()
    pdf_buffer.close()

    # --- Streamlit Download Button Target ---
    st.markdown("Click the button below to download the compiled PDF document report instantly:")
    st.download_button(
        label="📥 Download Analytical Report (PDF)",
        data=pdf_data,
        file_name=f"MCDM_Consensus_Top_{top_k}_Report.pdf",
        type="primary"
    )