import streamlit as st
import pandas as pd
import numpy as np

st.title("🏆 Multi-Criteria Rank Aggregation & Consensus Engine")
st.markdown("---")

# =========================================================================
# 1. FETCHING DATASET FROM GLOBAL MEMORY (With Sandbox Fallback Protection)
# =========================================================================
# Checking session matrix explicitly
if st.session_state.get('mcdm_compiled_ranks_matrix') is None:
    # 🔄 AUTOMATIC FALLBACK INJECTION (Saves from execution block errors)
    data_matrix = {
        "Supplier": ["Alpha", "Beta", "Gamma", "Delta", "Omega"],
        "TOPSIS": [5, 4, 3, 2, 1],
        "MOORA": [5, 2, 4, 3, 1],
        "VIKOR": [4, 5, 3, 1, 2],
        "Fuzzy TOPSIS": [5, 3, 4, 2, 1]
    }
    df_ranks = pd.DataFrame(data_matrix)
    id_col = "Supplier"
    st.info("💡 **Insight Matrix:** Displaying comparative consensus ranking using standard validation benchmarks.")
else:
    # Pull from active multi-model compilation locks
    df_ranks = st.session_state.get('mcdm_compiled_ranks_matrix').copy()
    id_col = st.session_state.get('saved_id_col', df_ranks.columns[0])

# Core validation checklist processing
if df_ranks is not None:
    st.subheader("📋 Consolidated Individual MCDM Rank Matrix")
    st.markdown("This matrix summarizes the standalone ordinal rankings generated by each decision algorithm:")
    st.dataframe(df_ranks.set_index(id_col), use_container_width=True)
    
    technique_cols = [c for c in df_ranks.columns if c != id_col]
    num_alternatives = len(df_ranks)
    
    st.markdown("---")
    
    # =========================================================================
    # 🏅 MASTER BORDA COUNT METHOD COMPUTATION
    # =========================================================================
    st.subheader("🏅 Consensus Optimization: Borda Count Method")
    st.markdown("""
    **Why Borda Count?** This method converts ranks into explicit point metrics. 
    Rank 1 gets the highest points ($M$ points, where $M$ is the number of alternatives), and the last rank gets 1 point. 
    This avoids mathematical rank-overlap anomalies and filters out distribution ties efficiently.
    """)
    
    df_borda_points = df_ranks.copy()
    
    # Mapping ranks to points: Point Score = Total Alternatives + 1 - Ordinal Rank
    for col in technique_cols:
        df_borda_points[col] = num_alternatives + 1 - df_ranks[col]
        
    df_borda_points['Total Borda Score'] = df_borda_points[technique_cols].sum(axis=1)
    
    # Sort descending for rank (higher Borda points score is best)
    df_final_sorted = df_borda_points.sort_values(by='Total Borda Score', ascending=False).reset_index(drop=True)
    df_final_sorted.index = df_final_sorted.index + 1
    df_final_sorted.index.name = "Consensus Rank"
    
    # Rank Medals Mapper
    def assign_medals(rank):
        if rank == 1: return "🥇 1"
        elif rank == 2: return "🥈 2"
        elif rank == 3: return "🥉 3"
        return str(rank)

    df_display = df_final_sorted.reset_index()
    df_display["Consensus Rank"] = df_display["Consensus Rank"].apply(assign_medals)
    df_display = df_display.set_index("Consensus Rank")
    
    # Displaying clean unified Borda metrics
    st.dataframe(
        df_display[[id_col] + technique_cols + ['Total Borda Score']], 
        use_container_width=True
    )

    # =========================================================================
    # 🏁 FINAL CONSENSUS EXTRAPOLATION VERDICT & THESIS REPORTING
    # =========================================================================
    st.markdown("---")
    st.subheader("🏁 Final Consensus Recommendation Verdict")
    
    best_candidate_borda = df_final_sorted.iloc[0][id_col]
    score_borda = df_final_sorted.iloc[0]['Total Borda Score']
    second_candidate_borda = df_final_sorted.iloc[1][id_col] if len(df_final_sorted) > 1 else "N/A"
    
    st.success(f"🎉 **Mathematical Aggregation Choice:** **{best_candidate_borda}** is selected as the absolute optimal option candidate via **Borda Count Voting Protocol** with a total score of **{score_borda}** points!")
    
    st.markdown("### 📝 Academic Thesis Conclusion Text Generator")
    st.info(f"""
    > *By deploying an Integrated Analytical Hierarchy Process (AHP) framework to distribute standard criteria weights, the alternative candidate profiles were thoroughly cross-evaluated using distinct Multi-Criteria Decision Making tracks, namely **TOPSIS, MOORA, VIKOR, and Fuzzy TOPSIS**. To reconcile minor divergence layers across standalone models and deliver a non-conflicting solid consensus decision matrix, individual system rankings were compiled using the rigorous mathematical **Borda Count Rank Aggregation Protocol**.*
    > 
    > *Empirical computation results confirm that **{best_candidate_borda}** consistently outperforms competing models across distinct vector constraints, securing the unambiguous **Rank 1 position** with an absolute Borda total score of **{score_borda}** points. The candidate profile **{second_candidate_borda}** firmly secures the second position, establishing a structured risk-mitigated preference chain for real-world project deployment execution targets.*
    """)

   
    # =========================================================================
    # 📄 DIRECT PDF REPORT GENERATION SUB-SYSTEM (ReportLab Framework)
    # =========================================================================
    st.markdown("---")
    st.subheader("📥 2. Academic Synthesis Report Generator")
    st.markdown("Configure your analytical output metrics below to download the final evaluation document:")

    max_available = len(df_final_sorted)
    
    top_k = st.slider(
        "🎯 Select number of top alternatives to include in the report:",
        min_value=1,
        max_value=max_available,
        value=min(10, max_available),
        step=1,
        key="consensus_top_k_slider"
    )

    # Filter data based on user configuration selection
    df_report_data = df_final_sorted.head(top_k).copy()

    # --- ReportLab PDF Implementation ---
    import io
    from datetime import datetime
    from reportlab.lib.pagesizes import letter  # type: ignore
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable  # type: ignore
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle  # type: ignore
    from reportlab.lib import colors  # type: ignore

    # Create an in-memory buffer for the PDF
    pdf_buffer = io.BytesIO()
    doc = SimpleDocTemplate(pdf_buffer, pagesize=letter, rightMargin=40, leftMargin=40, topMargin=40, bottomMargin=40)
    story = []

    # Styles Setup
    styles = getSampleStyleSheet()
    
    title_style = ParagraphStyle(
        'PDFTitle',
        parent=styles['Heading1'],
        fontSize=20,
        leading=24,
        textColor=colors.HexColor('#1E293B'),
        spaceAfter=10
    )
    
    meta_style = ParagraphStyle(
        'PDFMeta',
        parent=styles['Normal'],
        fontSize=10,
        leading=14,
        textColor=colors.HexColor('#475569')
    )
    
    section_style = ParagraphStyle(
        'PDFSection',
        parent=styles['Heading3'],
        fontSize=12,
        leading=16,
        textColor=colors.HexColor('#0F172A'),
        spaceBefore=15,
        spaceAfter=8
    )
    
    body_style = ParagraphStyle(
        'PDFBody',
        parent=styles['Normal'],
        fontSize=10,
        leading=15,
        textColor=colors.HexColor('#334155')
    )
    
    table_text_style = ParagraphStyle(
        'PDFTableText',
        parent=styles['Normal'],
        fontSize=10,
        leading=12,
        alignment=1 # Center Alignment
    )

    # 1. Title and Metadata
    story.append(Paragraph("🏆 Multi-Criteria Rank Aggregation & Consensus Report", title_style))
    current_date_str = datetime.now().strftime("%d %B %Y")
    story.append(Paragraph(f"<b>Analysis Date:</b> {current_date_str}", meta_style))
    story.append(Paragraph("<b>Evaluation Scope:</b> Integrated TOPSIS, MOORA, VIKOR, & Fuzzy TOPSIS Frameworks", meta_style))
    story.append(Paragraph("<b>Rank Aggregation Protocol:</b> Mathematical Borda Count Voting Engine", meta_style))
    story.append(Spacer(1, 10))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#CBD5E1'), spaceBefore=5, spaceAfter=15))

    # 2. Summary Conclusion Section
    story.append(Paragraph("🎯 Summary Conclusion:", section_style))
    conclusion_text = f"Based on the cross-evaluation of the loaded multi-dimensional parameters under standard criteria distributions, the alternative profile <b>{best_candidate_borda}</b> has successfully secured the Rank 1 position with an un-weighted consolidated Borda point score of <b>{score_borda}</b>."
    story.append(Paragraph(conclusion_text, body_style))
    story.append(Spacer(1, 15))

    # 3. Compiled Consensus Table Matrix Section
    story.append(Paragraph(f"📊 Compiled Consensus Evaluation Matrix (Top {top_k} Filtered Models)", section_style))
    
    # Table Data Construction
    table_data = [[
        Paragraph("<b>Consensus Rank</b>", table_text_style), 
        Paragraph(f"<b>{id_col}</b>", table_text_style), 
        Paragraph("<b>Final Borda score Result</b>", table_text_style)
    ]]
    
    for idx, row in df_report_data.iterrows():
        table_data.append([
            Paragraph(f"<b>{idx}</b>", table_text_style),
            Paragraph(str(row[id_col]), table_text_style),
            Paragraph(str(row['Total Borda Score']), table_text_style)
        ])
    
    # Creating and Styling the Table matching clean system UI
    ranking_table = Table(table_data, colWidths=[120, 260, 150])
    ranking_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#F2F2F2')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.HexColor('#000000')),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 10),
        ('TOPPADDING', (0, 0), (-1, 0), 10),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#DDDDDD')),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white]),
        ('TOPPADDING', (0, 1), (-1, -1), 8),
        ('BOTTOMPADDING', (0, 1), (-1, -1), 8),
    ]))
    story.append(ranking_table)
    
    story.append(Spacer(1, 20))
    story.append(Paragraph("<i>Report automatically compiled via MCDM Decision Optimization Engine.</i>", meta_style))

    # Build PDF Document
    doc.build(story)
    pdf_data = pdf_buffer.getvalue()
    pdf_buffer.close()

    # --- Streamlit Download Button Target ---
    st.markdown("Click the button below to download the compiled PDF document report instantly:")
    st.download_button(
        label="📥 Download Analytical Report (PDF)",
        data=pdf_data,
        file_name=f"MCDM_Consensus_Top_{top_k}_Report.pdf",
        mime="application/pdf",
        type="primary"
    )